(function() {var implementors = {};
implementors["icaros_base"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.TryFrom.html\" title=\"trait core::convert::TryFrom\">TryFrom</a>&lt;<a class=\"struct\" href=\"icaros_base/core/struct.GPSData.html\" title=\"struct icaros_base::core::GPSData\">GPSData</a>&gt; for <a class=\"struct\" href=\"icaros_base/core/struct.FullGPSData.html\" title=\"struct icaros_base::core::FullGPSData\">FullGPSData</a>","synthetic":false,"types":["icaros_base::core::FullGPSData"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.TryFrom.html\" title=\"trait core::convert::TryFrom\">TryFrom</a>&lt;<a class=\"struct\" href=\"icaros_base/comms/air/struct.CommandTypeInternal.html\" title=\"struct icaros_base::comms::air::CommandTypeInternal\">CommandTypeInternal</a>&gt; for <a class=\"enum\" href=\"icaros_base/comms/air/enum.A2GCommandType.html\" title=\"enum icaros_base::comms::air::A2GCommandType\">A2GCommandType</a>","synthetic":false,"types":["icaros_base::comms::air::A2GCommandType"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.TryFrom.html\" title=\"trait core::convert::TryFrom\">TryFrom</a>&lt;<a class=\"struct\" href=\"icaros_base/comms/air/struct.CommandTypeInternal.html\" title=\"struct icaros_base::comms::air::CommandTypeInternal\">CommandTypeInternal</a>&gt; for <a class=\"enum\" href=\"icaros_base/comms/air/enum.G2ACommandType.html\" title=\"enum icaros_base::comms::air::G2ACommandType\">G2ACommandType</a>","synthetic":false,"types":["icaros_base::comms::air::G2ACommandType"]}];
implementors["rf24"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.TryFrom.html\" title=\"trait core::convert::TryFrom\">TryFrom</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a>&gt; for <a class=\"enum\" href=\"rf24/enum.PowerAmplifierLevel.html\" title=\"enum rf24::PowerAmplifierLevel\">PowerAmplifierLevel</a>","synthetic":false,"types":["rf24::PowerAmplifierLevel"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.TryFrom.html\" title=\"trait core::convert::TryFrom\">TryFrom</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u32.html\">u32</a>&gt; for <a class=\"enum\" href=\"rf24/enum.DataRate.html\" title=\"enum rf24::DataRate\">DataRate</a>","synthetic":false,"types":["rf24::DataRate"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.TryFrom.html\" title=\"trait core::convert::TryFrom\">TryFrom</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u32.html\">u32</a>&gt; for <a class=\"enum\" href=\"rf24/enum.CRCLength.html\" title=\"enum rf24::CRCLength\">CRCLength</a>","synthetic":false,"types":["rf24::CRCLength"]}];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()