(function() {var implementors = {};
implementors["icaros"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"icaros/comms/application/struct.ApplicationID.html\" title=\"struct icaros::comms::application::ApplicationID\">ApplicationID</a>","synthetic":false,"types":["icaros::comms::application::ApplicationID"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"icaros/comms/application/struct.RequestID.html\" title=\"struct icaros::comms::application::RequestID\">RequestID</a>","synthetic":false,"types":["icaros::comms::application::RequestID"]}];
implementors["rf24"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"rf24/enum.SPISpeed.html\" title=\"enum rf24::SPISpeed\">SPISpeed</a>","synthetic":false,"types":["rf24::SPISpeed"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"rf24/enum.PowerAmplifierLevel.html\" title=\"enum rf24::PowerAmplifierLevel\">PowerAmplifierLevel</a>","synthetic":false,"types":["rf24::PowerAmplifierLevel"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"rf24/enum.DataRate.html\" title=\"enum rf24::DataRate\">DataRate</a>","synthetic":false,"types":["rf24::DataRate"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"rf24/enum.CRCLength.html\" title=\"enum rf24::CRCLength\">CRCLength</a>","synthetic":false,"types":["rf24::CRCLength"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"rf24/enum.RF24Error.html\" title=\"enum rf24::RF24Error\">RF24Error</a>","synthetic":false,"types":["rf24::RF24Error"]}];
implementors["rf24_sys"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rf24_sys/root/struct.SPISettings.html\" title=\"struct rf24_sys::root::SPISettings\">SPISettings</a>","synthetic":false,"types":["rf24_sys::root::SPISettings"]}];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()