name: Project Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo build for icaros
      uses: actions/cache@v1
      with:
        path: icaros/target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Nightly Rust
      uses: actions-rs/toolchain@v1.0.3
      with:
        toolchain: nightly
        override: true
    - name: Install external dependencies
      run: sudo apt-get install libudev-dev
    - name: Build icaros
      run: cargo build --verbose
      working-directory: icaros
    - name: Run icaros tests
      run: cargo test --verbose
      working-directory: icaros
    - name: Build icaros-control
      run: cargo build --verbose
      working-directory: icaros-control
    - name: Run icaros-control tests
      run: cargo test --verbose
      working-directory: icaros-control
