name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1 
    - run: cd icaros
    - name: Cache cargo build for icaros
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    - name: Build icaros
      run: cargo build --verbose
    - name: Run icaros tests
      run: cargo test --verbose

